### PR TITLE
Add support for hints, and more error checking.

### PR DESCRIPTION
**Pull request by pbiggar**

### CODE REVIEW

**Comment by seancorfield** [comment]
A question before I merge this: your PR allows `sort` with `one?` which was previously disallowed -- is that deliberate and does `sort` actually work with `one?` now?

**Comment by pbiggar** [comment]
@seancorfield I intended to leave that in. AFAICT, it's still there: https://github.com/aboekhoff/congomongo/pull/142/files#diff-765ac7a86553ec0191498c60e846537bR401

Am I missing something?

I left it in because there's a specific error message there and I thought it was more valuable than consolidating it.

**Comment by seancorfield** [comment]
Oops, sorry, I totally misread the diff. Yup, I'm just not awake yet :)

**Comment by seancorfield** [comment]
:+1:

**Comment by pbiggar** [comment]
Thanks!

Could I bother you for a release to clojars?

**Comment by seancorfield** [comment]
Done!

**Pull request merged**
